spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka
eureka:
  instance:
    prefer-ip-address: true

cloudinary:
  cloud-name: dd5fktvxv
  api-key: 824958365185222
  api-secret: KirmZyzS0qcIejGav_-VQBBmJ1A

gcloud:
  storage-bucket-name: p4-cs-linkedinapp
